
- name: prepare nodes
  hosts: kube
  tasks:
    - name: prepare nodes
      include_role:
        name: prepare-ubuntu



- name: init cluster
  hosts: masters[0]
  tasks:
    - shell: kubeadm init --pod-network-cidr=192.168.0.0/16  
    # - shell: kubeadm init --pod-network-cidr=192.168.0.0/16  --control-plane-endpoint={{ hostvars["kube-master-0"].ansible_host }}
      # register: join_command

    - name: generate join command 
      shell: |
        kubeadm token create --print-join-command 2>/dev/null | awk 'END{print $0}'
        mkdir /root/.kube
        cp /etc/kubernetes/admin.conf /root/.kube/config
      register: _join_command



- name: join nodes
  hosts: workers
  tasks:
    - name: Join control plane to k8s cluster with a token
      shell: "{{ hostvars[groups['masters'][0]]._join_command.stdout_lines[0] }}"





- name: install calico
  hosts: kube
  tasks:
    - include_role:
        name: cni-calico