---
apiVersion: v1
data:
  data: a=172.31.13.125:6789
  mapping: '{}'
  maxMonId: "2"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph-external