---
apiVersion: v1
data:
  admin-secret: QVFCOXZjMWgrWlNxQWhBQWxaR3E2cUFyNWMxSUdaZ3pveGZsUXc9PQ==
  # ceph-secret: ""
  # ceph-username: ""
  cluster-name: cm9vay1jZXBoLWV4dGVybmFs
  fsid: ZTgxMGViYWMtYjNlNi00NTA3LTkxODYtYTYzZDBiN2Q5MTFm
  mon-secret: bW9uLXNlY3JldA==
kind: Secret
metadata:
  creationTimestamp: null
  name: rook-ceph-mon
  namespace: rook-ceph-external
type: kubernetes.io/rook
---
apiVersion: v1
data:
  userID: Y3NpLXJiZC1ub2Rl
  userKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
type: kubernetes.io/rook
---
apiVersion: v1
data:
  userID: Y3NpLXJiZC1wcm92aXNpb25lcg==
  userKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph-external
type: kubernetes.io/rook
---
apiVersion: v1
data:
  adminID: Y3NpLWNlcGhmcy1ub2Rl
  adminKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
type: kubernetes.io/rook
---
apiVersion: v1
data:
  adminID: Y3NpLWNlcGhmcy1wcm92aXNpb25lcg==
  adminKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
type: kubernetes.io/rook
---
apiVersion: v1
data:
  accessKey: ""
  secretKey: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: rgw-admin-ops-user
  namespace: rook-ceph-external
type: kubernetes.io/rook