---
apiVersion: v1
kind: Pod
metadata:
  name: net-tools
  namespace: default
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: <any>
  containers:
  - name: net-tools
    image: praqma/network-multitool
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always